---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: Install core mysql resources
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - python-mysqldb
    - mysql-server-5.5

- name: Setup the root mysql user
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
  ignore_errors: true



- name: Install apt packages for git, nginx, and pip3
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - git
    - nginx
    - python3-pip

- name: Ensure the standard nginx.conf file is present and accounted for.
  copy:
    src: standardnginx.conf
    dest: /etc/nginx/nginx.conf

- name: copy the requirements file over
  copy:
    src: requirements.txt
    dest: /tmp/requirements.txt

- name: pip install the required python3 libs (including uwsgi)
  pip:
    executable: pip3
    requirements: /tmp/requirements.txt
